services:
  backend:
    build:
      context: ./services/backend
    restart: unless-stopped
    env_file:
      - backend.env
    depends_on:
      - mongo

  frontend:
    build:
      context: ./services/frontend
      args:
        NEXT_PUBLIC_API_BASE: https://api.softthat.fit
    restart: unless-stopped
    depends_on:
      - backend

  caddy:
    image: caddy:2.10
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./.data/caddy:/data
      - ./config/Caddyfile:/etc/caddy/Caddyfile
    depends_on:
      - frontend
      - backend

  mongo:
    image: mongo:8.2
    restart: unless-stopped
    volumes:
      - ./.data/mongo:/data/db