// Package oapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package oapi

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
	strictnethttp "github.com/oapi-codegen/runtime/strictmiddleware/nethttp"
)

// Defines values for ReportGetResponseStatus.
const (
	Failed  ReportGetResponseStatus = "failed"
	Pending ReportGetResponseStatus = "pending"
	Ready   ReportGetResponseStatus = "ready"
	Unknown ReportGetResponseStatus = "unknown"
)

// Issue defines model for Issue.
type Issue struct {
	Description string `json:"description"`
	Title       string `json:"title"`
}

// ProductMeta defines model for ProductMeta.
type ProductMeta struct {
	Alternatives     []string `json:"alternatives"`
	Classification   string   `json:"classification"`
	Name             string   `json:"name"`
	ShortDescription string   `json:"short_description"`
	Vendor           string   `json:"vendor"`
}

// ProductSecurityAssessment defines model for ProductSecurityAssessment.
type ProductSecurityAssessment struct {
	KeyIssues                  []Issue `json:"key_issues"`
	SecurityScore              string  `json:"security_score"`
	SecurityScoreJustification string  `json:"security_score_justification"`
	Summary                    string  `json:"summary"`
	Verdict                    string  `json:"verdict"`
}

// ReportContent defines model for ReportContent.
type ReportContent struct {
	Meta               ProductMeta               `json:"meta"`
	SecurityAssessment ProductSecurityAssessment `json:"security_assessment"`
}

// ReportGetResponse defines model for ReportGetResponse.
type ReportGetResponse struct {
	Content   *ReportContent          `json:"content,omitempty"`
	CreatedAt time.Time               `json:"created_at"`
	Id        string                  `json:"id"`
	Query     string                  `json:"query"`
	Status    ReportGetResponseStatus `json:"status"`
}

// ReportGetResponseStatus defines model for ReportGetResponse.Status.
type ReportGetResponseStatus string

// ReportStartResponse defines model for ReportStartResponse.
type ReportStartResponse struct {
	Id string `json:"id"`
}

// CreateReportJSONBody defines parameters for CreateReport.
type CreateReportJSONBody struct {
	// Query Query parameter for report generation
	Query string `json:"query"`
}

// CreateReportJSONRequestBody defines body for CreateReport for application/json ContentType.
type CreateReportJSONRequestBody CreateReportJSONBody

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Start report generation
	// (POST /report)
	CreateReport(w http.ResponseWriter, r *http.Request)
	// Get generated report
	// (GET /report/{id})
	GetReportByID(w http.ResponseWriter, r *http.Request, id string)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// Start report generation
// (POST /report)
func (_ Unimplemented) CreateReport(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get generated report
// (GET /report/{id})
func (_ Unimplemented) GetReportByID(w http.ResponseWriter, r *http.Request, id string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// CreateReport operation middleware
func (siw *ServerInterfaceWrapper) CreateReport(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateReport(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetReportByID operation middleware
func (siw *ServerInterfaceWrapper) GetReportByID(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetReportByID(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/report", wrapper.CreateReport)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/report/{id}", wrapper.GetReportByID)
	})

	return r
}

type CreateReportRequestObject struct {
	Body *CreateReportJSONRequestBody
}

type CreateReportResponseObject interface {
	VisitCreateReportResponse(w http.ResponseWriter) error
}

type CreateReport200JSONResponse ReportStartResponse

func (response CreateReport200JSONResponse) VisitCreateReportResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type CreateReport500JSONResponse struct {
	Error *string `json:"error,omitempty"`
}

func (response CreateReport500JSONResponse) VisitCreateReportResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type GetReportByIDRequestObject struct {
	Id string `json:"id"`
}

type GetReportByIDResponseObject interface {
	VisitGetReportByIDResponse(w http.ResponseWriter) error
}

type GetReportByID200JSONResponse ReportGetResponse

func (response GetReportByID200JSONResponse) VisitGetReportByIDResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetReportByID400JSONResponse struct {
	Error *string `json:"error,omitempty"`
}

func (response GetReportByID400JSONResponse) VisitGetReportByIDResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type GetReportByID404JSONResponse struct {
	Error *string `json:"error,omitempty"`
}

func (response GetReportByID404JSONResponse) VisitGetReportByIDResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type GetReportByID500JSONResponse struct {
	Error *string `json:"error,omitempty"`
}

func (response GetReportByID500JSONResponse) VisitGetReportByIDResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// Start report generation
	// (POST /report)
	CreateReport(ctx context.Context, request CreateReportRequestObject) (CreateReportResponseObject, error)
	// Get generated report
	// (GET /report/{id})
	GetReportByID(ctx context.Context, request GetReportByIDRequestObject) (GetReportByIDResponseObject, error)
}

type StrictHandlerFunc = strictnethttp.StrictHTTPHandlerFunc
type StrictMiddlewareFunc = strictnethttp.StrictHTTPMiddlewareFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// CreateReport operation middleware
func (sh *strictHandler) CreateReport(w http.ResponseWriter, r *http.Request) {
	var request CreateReportRequestObject

	var body CreateReportJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CreateReport(ctx, request.(CreateReportRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateReport")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CreateReportResponseObject); ok {
		if err := validResponse.VisitCreateReportResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetReportByID operation middleware
func (sh *strictHandler) GetReportByID(w http.ResponseWriter, r *http.Request, id string) {
	var request GetReportByIDRequestObject

	request.Id = id

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetReportByID(ctx, request.(GetReportByIDRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetReportByID")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetReportByIDResponseObject); ok {
		if err := validResponse.VisitGetReportByIDResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/8RWT2/7Ngz9Koa2o5dkW3bJ7fcHK3IY1rXHIghUi27U2pJL0tmMwN99kBSndiw3bbFi",
	"N1umyMfH9yQfRGbLyhowTGJ1EJTtoJT+cU1Ug3uo0FaArMEvK6AMdcXaGvfKTQViJYhRmwfRpoI1FxD5",
	"0qYC4bnWCEqs7o5h6SDdJu022ftHyNilu0ar6oz/AJYuqVRKu1hZXPdQ5bIgSIWpi0Leu+qMNaRnwGXB",
	"gEay3od3zVBSvIWwIBFl496zQhLpXGdysmsjS4h+oJ1F3l4ibQ9GWbzMmi9zCh8hi5VLh42/wvEtZDVq",
	"br4QAVEJhi8yPmT4CZqtdqoZ8iuL4s9crO4O4keEXKzED/MX0c2PipsHubWbCP90BLalzOIEzYOQ7WNN",
	"/PrAqC5Lic3ENFDpjC+Po0uS9lt/2T9CfgFnbDY3UFnkb9bw++dRdqZ50wD6TvNjOGGVQ0G8J1tEU+3m",
	"nEaPM15vmpIr4BugyhqKHFJZj683wR3S7NvPECSD2kqfJrdYuiehJMNPrL0PR8rRKiqo5xompEYsufaQ",
	"wdSlI6M2T8b+7XxbgVEuzJEllVNZLnUBqkfKhC61El3RU4lBQ9O03rLEV4iNNjiuPs7vgrTJrd8erghB",
	"NmesiYNlyFtVLGY/zxYOj63AyEqLlfh1tpgtHSGSdx7FHD1WD88Sj64l4bugRFJjsiQEJw9gAL3REmlU",
	"gsA1Gkp4B12EVjPh64awtRIr8c2TFrgRoU8g/mpVc66zqiqORp4/Ujh1grrGLJ70MET9l1tOKomyBAZM",
	"cotj8OLS8EPy+ARe4twN6RfCpD2sXxaLdzV12VBDNXkIw5ZDWOKl6SeTZVAxKCeA394EB/6RZRX+OADR",
	"XaLid2+ThG1Crn6EQ+e8idkck8REHiF02M3a+Ju2SAhwD5iEXG3/ugnSjEFq007X84NWrYPwABFt34yF",
	"GxAl901Uwv6kdHFfm/V3b6OjwMgfi9olddYS3W9MOD+GWukTds7M5tN11D/sI7x/GRLhxrv8qHjWZi8L",
	"rbqM6++fJ5ZIoeVi+THYRyMZy0lua6M+C3Wszn9gVARGDftO0f+nQa/g5EtQJzxt2/4bAAD//9Id0fMs",
	"DQAA",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
